modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="diolib"
version="${file.jarVersion}"
displayName="Diabolo Lib"
logoFile="diabolo-lib.png"
authors="AlasDiablo, lIotaMiu & Safyrus"
description='''
Libray Mod for Janoeo Project and more !
'''
[[dependencies.diolib]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.diolib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
