modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
[[mods]]
modId="diabolo"
version="${file.jarVersion}"
displayName="Diabolo Lib"
logoFile="diabolo-lib.png"
authors="AlasDiablo, lIotaMiu & Safyrus"
description='''
Libray Mod for Janoeo Project and more !
'''
[[dependencies.diabolo]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.diabolo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
